/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.interfaces;

import com.proyecto.manejadores.ManejadorSuelo;
import com.proyecto.suelo.Granja;
import java.awt.GridLayout;
import javax.swing.WindowConstants;

/**
 *
 * @author davis
 */

public class GranjaJFrame extends javax.swing.JFrame {
private ManejadorSuelo manejadorSuelo;
private Granja granja;
    /**
     * Creates new form SueloJFrame
     */
    public GranjaJFrame() {
        initComponents();
        this.setTitle("Granja");
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.sueloPanel.setLayout(new GridLayout(5,5));

        this.granja = new Granja();
        manejadorSuelo = new ManejadorSuelo(sueloPanel, granja.getSuelo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sueloPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout sueloPanelLayout = new javax.swing.GroupLayout(sueloPanel);
        sueloPanel.setLayout(sueloPanelLayout);
        sueloPanelLayout.setHorizontalGroup(
            sueloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        sueloPanelLayout.setVerticalGroup(
            sueloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sueloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sueloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel sueloPanel;
    // End of variables declaration//GEN-END:variables
}
