/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.interfaces;

import com.proyecto.manejadores.ManejadorSuelo;
import com.proyecto.persona.Granjero;
import com.proyecto.suelo.Granja;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author davis
 */

public class GranjaJFrame extends javax.swing.JFrame {
/**
* Manejador suelo
*/
private ManejadorSuelo manejadorSuelo;
/**
 * Granja
 */
private Granja granja;

/**
 * filas
 */
private int filas ; 
/**
 * columnas
 */
private int columnas ; 
/**
 * Granjero
 */
private Granjero granjero;
/**
 * MercadoJFrame
 */
private MercadoJFrame mercado;

private ReportesJFrame reportes;
private Bodega bodega;


    /**
     * Constructor de la granja
     * @param filas int filas
     * @param columnas int columnas
     * @param granjero granjero
     */
    public GranjaJFrame(int filas, int columnas, Granjero granjero) {
        this.granjero = granjero;
        this.filas = filas;
        this.columnas = columnas;
        this.mercado = new MercadoJFrame(this.granjero);  //se creo una ventana nueva para el mercado que se llamara despues
        this.reportes = new ReportesJFrame(this.granjero); //se creo una ventana nueva para el reporte que se llamara despues
        this.bodega = new Bodega(this.granjero);
        this.granjero.getBotonJLabel1().setText("Oro: "+ this.granjero.getOro());
        
       
        
        
        initComponents();
        this.setTitle("Granja");
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.sueloPanel.setLayout(new GridLayout(filas,columnas));
        
        this.granja = new Granja(filas,columnas);
        manejadorSuelo = new ManejadorSuelo(sueloPanel, granja.getSuelo(), filas,columnas); //filas 5 columnas 5
        nombreLabel.setText(this.granjero.getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sueloPanel = new javax.swing.JPanel();
        tiendaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        reporteLabel = new javax.swing.JLabel();
        comerLabel = new javax.swing.JLabel();
        bodegaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        javax.swing.GroupLayout sueloPanelLayout = new javax.swing.GroupLayout(sueloPanel);
        sueloPanel.setLayout(sueloPanelLayout);
        sueloPanelLayout.setHorizontalGroup(
            sueloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        sueloPanelLayout.setVerticalGroup(
            sueloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tiendaLabel.setText("Tienda");
        tiendaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiendaLabelMouseClicked(evt);
            }
        });

        nombreLabel.setText("Nick");

        reporteLabel.setText("Info.");
        reporteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteLabelMouseClicked(evt);
            }
        });

        comerLabel.setText("Comer");
        comerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comerLabelMouseClicked(evt);
            }
        });

        bodegaLabel.setText("Bodega");
        bodegaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bodegaLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reporteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodegaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(sueloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tiendaLabel)
                .addGap(31, 31, 31)
                .addComponent(reporteLabel)
                .addGap(29, 29, 29)
                .addComponent(comerLabel)
                .addGap(27, 27, 27)
                .addComponent(bodegaLabel)
                .addContainerGap(90, Short.MAX_VALUE))
            .addComponent(sueloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * LLama al Frame de tienda
     */
    private void tiendaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiendaLabelMouseClicked
        System.out.println("Dirigido a la tienda");// Aqui iran los metodos para la tienda
        //int oroNuevo = this.granjero.getOro() - 5 ;
        System.out.println("Te desconte 5 de oro");
        //this.granjero.setOro(oroNuevo);
        this.granjero.getBotonJLabel1().setText("Oro: "+ this.granjero.getOro());
        this.mercado.setVisible(true); // hago q el mercado aparezca jujujujuju
        
        
    }//GEN-LAST:event_tiendaLabelMouseClicked
    /**
     * LLamara al frame de reportes
     * 
     */
    private void reporteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteLabelMouseClicked
        this.reportes.setVisible(true); //Hago mostrar el frame de repportes
        
    }//GEN-LAST:event_reporteLabelMouseClicked
    /**
     * Metodo para q coma el granjero + 10 de vida por click
     */
    private void comerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comerLabelMouseClicked
        // TODO add your handling code here:
        if((this.granjero.getVida())<=90 && this.granjero.getVida()>0){
            this.granjero.setVida(this.granjero.getVida()+10);
            JOptionPane.showMessageDialog(null, "Ganaste 10 de vida");
        }
        else{
            JOptionPane.showMessageDialog(null, "No puedes comer");
        }
    }//GEN-LAST:event_comerLabelMouseClicked
    /**
     * Me dirigira a la bodega
     * @param evt 
     */
    private void bodegaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodegaLabelMouseClicked
        // TODO add your handling code here:
        this.bodega.setVisible(true);
    }//GEN-LAST:event_bodegaLabelMouseClicked

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bodegaLabel;
    private javax.swing.JLabel comerLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel reporteLabel;
    private javax.swing.JPanel sueloPanel;
    private javax.swing.JLabel tiendaLabel;
    // End of variables declaration//GEN-END:variables
}
