/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.interfaces;

import com.proyecto.manejadores.ManejadorSuelo;
import com.proyecto.persona.Granjero;
import com.proyecto.suelo.Granja;
import java.awt.GridLayout;
import javax.swing.WindowConstants;

/**
 *
 * @author davis
 */

public class GranjaJFrame extends javax.swing.JFrame {
/**
* Manejador suelo
*/
private ManejadorSuelo manejadorSuelo;
/**
 * Granja
 */
private Granja granja;

/**
 * filas
 */
private int filas ; 
/**
 * columnas
 */
private int columnas ; 
/**
 * Granjero
 */
private Granjero granjero;
/**
 * MercadoJFrame
 */
private MercadoJFrame mercado;


    /**
     * Constructor de la granja
     * @param filas int filas
     * @param columnas int columnas
     * @param granjero granjero
     */
    public GranjaJFrame(int filas, int columnas, Granjero granjero) {
        this.mercado = new MercadoJFrame();
        this.granjero = granjero;
        this.filas = filas;
        this.columnas = columnas;
        initComponents();
        this.setTitle("Granja");
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.sueloPanel.setLayout(new GridLayout(filas,columnas));
        
        this.granja = new Granja(filas,columnas);
        manejadorSuelo = new ManejadorSuelo(sueloPanel, granja.getSuelo(), filas,columnas); //filas 5 columnas 5
        nombreLabel.setText(granjero.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sueloPanel = new javax.swing.JPanel();
        tiendaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        javax.swing.GroupLayout sueloPanelLayout = new javax.swing.GroupLayout(sueloPanel);
        sueloPanel.setLayout(sueloPanelLayout);
        sueloPanelLayout.setHorizontalGroup(
            sueloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        sueloPanelLayout.setVerticalGroup(
            sueloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tiendaLabel.setText("Tienda");
        tiendaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiendaLabelMouseClicked(evt);
            }
        });

        nombreLabel.setText("Nick");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(sueloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tiendaLabel)
                .addGap(47, 225, Short.MAX_VALUE))
            .addComponent(sueloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * LLama al Frame de tienda
     */
    private void tiendaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiendaLabelMouseClicked
        System.out.println("Dirigido a la tienda");// Aqui iran los metodos para la tienda
        int oroNuevo = granjero.getOro() - 5 ;
        System.out.println("Te desconte 5 de oro");
        granjero.setOro(oroNuevo);
        
        this.mercado.setVisible(true); // hago q el mercado aparezca jujujujuju
        
        
    }//GEN-LAST:event_tiendaLabelMouseClicked

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel sueloPanel;
    private javax.swing.JLabel tiendaLabel;
    // End of variables declaration//GEN-END:variables
}
