/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.interfaces;

import com.proyecto.persona.Granjero;


/**
 *
 * @author davis
 */
public class ReportesJFrame extends javax.swing.JFrame {
private Granjero granjero;
    /**
     * Reportes partida
     * @param granjero objeto granjero
     */
    public ReportesJFrame(Granjero granjero) {
        this.granjero = granjero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        animalLabel = new javax.swing.JLabel();
        partidaLabel = new javax.swing.JLabel();
        plantasLabel = new javax.swing.JLabel();
        textoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        animalLabel.setText("Reporte de Animales");
        animalLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animalLabelMouseClicked(evt);
            }
        });

        partidaLabel.setText("Resumen de partidas");
        partidaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partidaLabelMouseClicked(evt);
            }
        });

        plantasLabel.setText("Reporte de plantas");
        plantasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantasLabelMouseClicked(evt);
            }
        });

        textoLabel.setText("Informacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(animalLabel)
                    .addComponent(partidaLabel)
                    .addComponent(plantasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(partidaLabel)
                        .addGap(67, 67, 67)
                        .addComponent(animalLabel)
                        .addGap(59, 59, 59)
                        .addComponent(plantasLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(textoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    
    
    /**
     * Evento para mostrar info de la partida
     * 
     */
    private void partidaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partidaLabelMouseClicked
        textoLabel.setText(getTexto1(this.granjero));
    }//GEN-LAST:event_partidaLabelMouseClicked
    /**
     * Evento para mostrar info de los animales
     *
     */
    private void animalLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalLabelMouseClicked
        // TODO add your handling code here:
        textoLabel.setText(getTexto2(granjero));
    }//GEN-LAST:event_animalLabelMouseClicked
    /**
     * Evento para mostrar info de las plantas 
     */
    private void plantasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantasLabelMouseClicked
        // TODO add your handling code here:
        textoLabel.setText(getTexto3(granjero));
    }//GEN-LAST:event_plantasLabelMouseClicked
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animalLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel partidaLabel;
    private javax.swing.JLabel plantasLabel;
    private javax.swing.JLabel textoLabel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Este metodo devolvera el texto 1  
     * @param granjero objeto granjero
     * @return texto1
     */
    public String getTexto1(Granjero granjero){
        this.granjero = granjero;
        
        return "Nombre: " + this.granjero.getNombre() + " Tiempo P: " + this.granjero.getTiempo()+" seg";
    }
    /**
     * Este metodo devolvera el texto 2 
     * @param granjero objeto granjero
     * @return texto2
     */
    public String getTexto2(Granjero granjero){
        this.granjero = granjero;
        
        return "Cantidad animales comprados: " + this.granjero.getPlantas().length;//.getNombre();;
    }
    /**
     * Este metodo devolvera el texto 3  
     * @param granjero objeto granjero
     * @return texto3
     */
    public String getTexto3(Granjero granjero){
        this.granjero = granjero;
        
        
        return "Cantidad Semillas compradas: " + this.granjero.getPlantas().length;//.getNombre();
    }

}
